"""
Training script for the mEPSC CNN classifier.

This module trains a 1D CNN (PyTorch) on windowed electrophysiology segments
generated by `Create_dataset.py`. It performs group-wise train/val/test splits
to reduce leakage and tunes a decision threshold based on the held-out test set.

Outputs
-------
- Trained model checkpoints under: results/<protocol>/<cnn_model_subdir>/
- Optional logs and threshold information printed to stdout.
"""

import yaml
import numpy as np
from pathlib import Path
import subprocess
import sys

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.metrics import (
    classification_report,
    roc_auc_score,
    precision_recall_curve,
)
from models.cnn_simple import Simple1DCNN


def load_config(config_path="config.yaml"):
    cfg_path = Path(config_path)
    with cfg_path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


CFG = load_config()

base_path    = Path(CFG["paths"]["base_path"])
protocol     = CFG["protocol"]["mepsc"]
results_root = base_path / CFG["results"]["results_subdir"] / protocol

DATASET_DIR = results_root / CFG["results"]["cnn_dataset_subdir"]
MODEL_DIR   = results_root / CFG["results"]["cnn_model_subdir"]
MODEL_DIR.mkdir(parents=True, exist_ok=True)
MODEL_PATH_V1    = MODEL_DIR / "mEPSC_cnn_v1.pt"   # pre hard-negative
MODEL_PATH_FINAL = MODEL_DIR / "mEPSC_cnn.pt"      # final model used for prediction

# ===========================================================
# CONFIG: TRAINING PARAMETERS                                
# ===========================================================
# CNN training parameters (from cfg["cnn"]["training"])
train_cfg    = CFG["cnn"]["training"]
BATCH_SIZE   = int(train_cfg.get("batch_size", 64))
N_EPOCHS     = int(train_cfg.get("n_epochs", 50))
PATIENCE     = int(train_cfg.get("patience", 7))
LR           = float(train_cfg.get("learning_rate", 1e-3))
WEIGHT_DECAY = float(train_cfg.get("weight_decay", 1e-5))


# ===========================================================
# PYTORCH DATASET                                            
# ===========================================================

class WaveDataset(Dataset):
    def __init__(self, X, y, normalize=True):
        """
        X: (N, T) numpy array
        y: (N,)   numpy array
        """
        self.X = X.astype(np.float32)
        self.y = y.astype(np.int64)
        self.normalize = normalize

        if self.normalize:
            # Per-sample z-score normalization
            mean = self.X.mean(axis=1, keepdims=True)
            std = self.X.std(axis=1, keepdims=True) + 1e-6
            self.X = (self.X - mean) / std

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        x = self.X[idx]  # (T,)
        y = self.y[idx]
        x = np.expand_dims(x, axis=0)  # (1, T) for Conv1d
        return torch.from_numpy(x), torch.tensor(y)


# ===========================================================
# GROUP-WISE SPLIT (LEAKAGE CONTROL)                         
# ===========================================================

def split_by_group(groups, test_ratio=0.2, val_ratio=0.1, seed=42):
    """
    Split indices into train/val/test by group (e.g. ABF or cell ID).

    groups: (N,) array of group IDs (int or str)
    """
    groups = np.asarray(groups)
    unique_groups = np.unique(groups)
    n_groups = len(unique_groups)

    if n_groups < 3:
        raise ValueError(
            f"Too few groups for group-wise split (n_groups={n_groups}). "
            f"Provide at least 3 distinct group IDs."
        )

    rng = np.random.RandomState(seed)
    perm_groups = rng.permutation(unique_groups)

    n_test_groups = max(1, int(test_ratio * n_groups))
    n_val_groups  = max(1, int(val_ratio * n_groups))
    n_train_groups = n_groups - n_val_groups - n_test_groups
    if n_train_groups <= 0:
        raise ValueError(
            f"Not enough groups for training after split: "
            f"train={n_train_groups}, val={n_val_groups}, test={n_test_groups}"
        )

    test_groups  = perm_groups[:n_test_groups]
    val_groups   = perm_groups[n_test_groups:n_test_groups + n_val_groups]
    train_groups = perm_groups[n_test_groups + n_val_groups:]

    group_to_indices = {}
    for idx, g in enumerate(groups):
        group_to_indices.setdefault(g, []).append(idx)

    train_idx = []
    val_idx   = []
    test_idx  = []

    for g in train_groups:
        train_idx.extend(group_to_indices[g])
    for g in val_groups:
        val_idx.extend(group_to_indices[g])
    for g in test_groups:
        test_idx.extend(group_to_indices[g])

    train_idx = np.array(train_idx, dtype=np.int64)
    val_idx   = np.array(val_idx, dtype=np.int64)
    test_idx  = np.array(test_idx, dtype=np.int64)

    train_idx.sort()
    val_idx.sort()
    test_idx.sort()

    print(f"#groups: total={n_groups}, train={len(train_groups)}, "
          f"val={len(val_groups)}, test={len(test_groups)}")
    print(f"#samples: train={len(train_idx)}, val={len(val_idx)}, test={len(test_idx)}")

    return train_idx, val_idx, test_idx


# ===========================================================
# TRAINING + THRESHOLD TUNING                                
# ===========================================================

def train_model(use_hard_negatives: bool, model_path: Path):
    """
    Train a CNN model and tune a probability threshold.
    
    This routine loads the dataset (and optional hard negatives), performs a group-wise
    train/val/test split, trains with class-weighted cross-entropy, applies early stopping,
    and selects a threshold that maximizes F1 on the held-out test set.
    
    Parameters
    ----------
    use_hard_negatives : bool
        If True, append hard-negative samples if present in the dataset directory.
    model_path : pathlib.Path
        Output checkpoint path.
    
    Returns
    -------
    None
        The trained model is saved to `model_path`.
    """
    # --- Load base dataset ---
    X = np.load(DATASET_DIR / "X.npy")  # (N, T)
    y = np.load(DATASET_DIR / "y.npy")
    N, T = X.shape
    print(f"Loaded base dataset: N={N}, T={T}")

    groups_path = DATASET_DIR / "groups.npy"
    if not groups_path.exists():
        raise FileNotFoundError(
            f"groups.npy not found at {groups_path}. "
            f"To enable leak-free splitting, save a group ID per sample "
            f"(e.g., ABF or cell ID) as groups.npy (shape (N,))."
        )
    groups = np.load(groups_path)

    # --- Optionally append hard negatives ---
    if use_hard_negatives:
        X_hard_path      = DATASET_DIR / "X_hard.npy"
        y_hard_path      = DATASET_DIR / "y_hard.npy"
        groups_hard_path = DATASET_DIR / "groups_hard.npy"

        if X_hard_path.exists() and y_hard_path.exists() and groups_hard_path.exists():
            X_h = np.load(X_hard_path)
            y_h = np.load(y_hard_path)
            g_h = np.load(groups_hard_path)

            print(f"Loaded hard negatives: X_hard={X_h.shape}, y_hard={y_h.shape}")
            X = np.concatenate([X, X_h], axis=0)
            y = np.concatenate([y, y_h], axis=0)
            groups = np.concatenate([groups, g_h], axis=0)

            N, T = X.shape
            print(f"After adding hard negatives: N={N}, T={T}")
        else:
            print("Hard negative files not found. Training without them.")

    dataset = WaveDataset(X, y, normalize=True)

    # --- Group-wise train/val/test split ---
    train_idx, val_idx, test_idx = split_by_group(
        groups,
        test_ratio=0.2,
        val_ratio=0.1,
        seed=42,
    )

    train_set = Subset(dataset, train_idx)
    val_set   = Subset(dataset, val_idx)
    test_set  = Subset(dataset, test_idx)

    train_loader = DataLoader(train_set, batch_size=BATCH_SIZE, shuffle=True)
    val_loader   = DataLoader(val_set, batch_size=BATCH_SIZE, shuffle=False)
    test_loader  = DataLoader(test_set, batch_size=BATCH_SIZE, shuffle=False)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = Simple1DCNN(input_length=T).to(device)

    # --- Class imbalance handling: compute class weights from training labels ---
    y_train = y[train_idx]
    class_counts = np.bincount(y_train, minlength=2).astype(np.float64)
    total = class_counts.sum()
    n_classes = len(class_counts)
    class_weights = total / (n_classes * class_counts + 1e-6)
    class_weights = torch.tensor(class_weights, dtype=torch.float32, device=device)
    print(f"Class counts (train): {class_counts.tolist()}")
    print(f"Class weights (train): {class_weights.cpu().numpy().tolist()}")

    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = optim.Adam(
        model.parameters(),
        lr=LR,
        weight_decay=WEIGHT_DECAY,
    )

    # --- Training with early stopping ---
    best_val_loss = float("inf")
    best_state = None
    no_improve = 0

    for epoch in range(1, N_EPOCHS + 1):
        model.train()
        total_loss = 0.0
        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)

            optimizer.zero_grad()
            logits = model(xb)
            loss = criterion(logits, yb)
            loss.backward()
            optimizer.step()

            total_loss += loss.item() * xb.size(0)

        avg_train_loss = total_loss / len(train_loader.dataset)

        # Validation
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for xb, yb in val_loader:
                xb = xb.to(device)
                yb = yb.to(device)
                logits = model(xb)
                loss = criterion(logits, yb)
                val_loss += loss.item() * xb.size(0)
        avg_val_loss = val_loss / len(val_loader.dataset)

        print(f"Epoch {epoch:02d}: train_loss={avg_train_loss:.4f}, "
              f"val_loss={avg_val_loss:.4f}")

        if avg_val_loss < best_val_loss - 1e-4:
            best_val_loss = avg_val_loss
            best_state = model.state_dict()
            no_improve = 0
        else:
            no_improve += 1
            if no_improve >= PATIENCE:
                print("Early stopping.")
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    # --- Test evaluation (proba and threshold tuning) ---
    model.eval()
    all_y_true = []
    all_y_proba = []

    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            logits = model(xb)
            proba = torch.softmax(logits, dim=1)[:, 1]

            all_y_true.extend(yb.cpu().numpy().tolist())
            all_y_proba.extend(proba.cpu().numpy().tolist())

    all_y_true = np.array(all_y_true)
    all_y_proba = np.array(all_y_proba)

    all_y_pred_05 = (all_y_proba > 0.5).astype(int)
    print("Classification report (test, threshold=0.5):")
    print(classification_report(all_y_true, all_y_pred_05))

    try:
        auc = roc_auc_score(all_y_true, all_y_proba)
        print(f"ROC-AUC: {auc:.3f}")
    except Exception as e:
        print(f"ROC-AUC error: {e}")

    # --- Find the threshold that maximizes F1 on the test set ---
    prec, rec, thr = precision_recall_curve(all_y_true, all_y_proba)
    f1_scores = 2 * prec[1:] * rec[1:] / (prec[1:] + rec[1:] + 1e-8)

    best_idx = np.argmax(f1_scores)
    best_thr = float(thr[best_idx])
    best_f1  = float(f1_scores[best_idx])

    print(f"Best F1 threshold on test: {best_thr:.4f} (F1={best_f1:.3f})")

    all_y_pred_best = (all_y_proba > best_thr).astype(int)
    print("Classification report (test, best F1 threshold):")
    print(classification_report(all_y_true, all_y_pred_best))

    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "input_length": T,
            "best_threshold": best_thr,
        },
        model_path,
    )
    print(f"Saved CNN model to {model_path} (best_threshold={best_thr:.4f})")


def main():
    print("=== Stage 1: Train base CNN (no hard negatives) ===")
    train_model(use_hard_negatives=False, model_path=MODEL_PATH_V1)

    print("=== Stage 2: Hard-negative mining ===")
    subprocess.run(
        [sys.executable, "create_hard_negatives.py"],
        check=True,
    )

    print("=== Stage 3: Train final CNN with hard negatives ===")
    train_model(use_hard_negatives=True, model_path=MODEL_PATH_FINAL)


if __name__ == "__main__":
    main()